# name: Deploy SAM Application

# on:
#   push:
#     branches:
#       - main
#       - develop

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
    
#     steps:
#       - uses: actions/checkout@v3
      
#       - name: Set up JDK 21
#         uses: actions/setup-java@v3
#         with:
#           java-version: '21'
#           distribution: 'temurin'

#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v2
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1  # Change as needed

#       - name: Install SAM CLI
#         run: |
#           pip install aws-sam-cli

#       - name: Build SAM Application
#         run: |
#           mvn clean package
#           sam build

#       - name: Deploy to Development
#         if: github.ref == 'refs/heads/develop'
#         run: |
#           sam deploy \
#             --stack-name s3-email-dev \
#             --parameter-overrides Environment=dev \
#             --capabilities CAPABILITY_IAM \
#             --no-fail-on-empty-changeset

#       - name: Deploy to Production
#         if: github.ref == 'refs/heads/main'
#         run: |
#           sam deploy \
#             --stack-name s3-email-prod \
#             --parameter-overrides Environment=prod \
#             --capabilities CAPABILITY_IAM \
#             --no-fail-on-empty-changeset